### ISSUE TITLE
MonoMod.Backports conflicts with System.Memory and Polyfill packages on .NET Framework 4.8

### ISSUE THREAD

**Issue by Metadorius** [AngelDE98/MonoMod#167] opened 2024-02-05 12:04 UTC
### Description

I need to use polyfills that are defined by the Polyfill package and also need runtime detours in my project. When adding both of them, including the optional dependency `System.Memory`, compile errors appear because of doubly defined types.

```
...
0>Polyfill_Memory.cs(22,14): Error CS0433 : The type 'ReadOnlySpan<T>' exists in both 'MonoMod.Backports, Version=23.3.22.1, Culture=neutral, PublicKeyToken=null' and 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
0>Polyfill_Memory.cs(44,14): Error CS0433 : The type 'Span<T>' exists in both 'MonoMod.Backports, Version=23.3.22.1, Culture=neutral, PublicKeyToken=null' and 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
...
0>DynamicDependencyAttribute.cs(108,12): Warning CS0436 : The type 'DynamicallyAccessedMemberTypes' in 'C:\Users\Rius\.nuget\packages\polyfill\2.1.0\contentFiles\cs\netstandard2.0\Polyfill\Trimming\DynamicallyAccessedMemberTypes.cs' conflicts with the imported type 'DynamicallyAccessedMemberTypes' in 'MonoMod.Backports, Version=23.3.22.1, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\Rius\.nuget\packages\polyfill\2.1.0\contentFiles\cs\netstandard2.0\Polyfill\Trimming\DynamicallyAccessedMemberTypes.cs'.
...
```

### Example

I omitted whatever is irrelevant to issue reproduction from the project file.

```xml

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <PolyPublic>true</PolyPublic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polyfill" Version="2.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ValueTuple"
                      Version="4.5.0"
                      Condition="$(TargetFramework.StartsWith('net46'))" />
    <PackageReference Include="System.Memory"
                      Version="4.5.5"
                      Condition="$(TargetFrameworkIdentifier) == '.NETStandard' or
                             $(TargetFrameworkIdentifier) == '.NETFramework' or
                             $(TargetFramework.StartsWith('netcoreapp2'))" />
    <PackageReference Include="System.Threading.Tasks.Extensions"
                      Version="4.5.4"
                      Condition="$(TargetFramework) == 'netstandard2.0' or
                             $(TargetFramework) == 'netcoreapp2.0' or
                             $(TargetFrameworkIdentifier) == '.NETFramework'" />
    <PackageReference Include="MonoModReorg.RuntimeDetour" Version="23.3.22.1" />
  </ItemGroup>
```

**Comment by nike4613** [comment] 2024-02-05 12:44
`MonoModReorg.*` is long out of date. Use `MonoMod.*`.

Otherwise, this is a duplicate of #146, and is by-design. 

It seems to me that the `Polyfill` package's functionality is entirely subsumed by Backports + `PolySharp` (the latter of which has the benefit of not needing external packages, and the former has a larger support matrix).

**Closed as not planned by nike4613** 2024-02-05 12:44 UTC
Labels: bug

**Comment by Metadorius** [comment] 2024-02-05 13:05
No difference in behavior between Reorg and regular version.

Even if I remove the System.Memory reference, it still errors with the same output.

> It seems to me that the Polyfill package's functionality is entirely subsumed by Backports + PolySharp (the latter of which has the benefit of not needing external packages, and the former has a larger support matrix).

Not sure of this, IIRC when I needed polyfills on another project it had some of the features that other packages didn't, and regardless doesn't seem to be good to force switching consumers to alternative packages.
