### ISSUE TITLE
Add strongname to make all projects can use this library

### ISSUE THREAD

**Issue by CreateAndInject** [AngelDE98/MonoMod#144] opened 2023-10-11 23:44 UTC
Suggestion from Microsoft:
> You should strong name your open-source .NET libraries. Strong naming an assembly ensures the most people can use it, and strict assembly loading only affects .NET Framework.

MonoMod isn't signed, it causes all projects depend on it can't be signed, eg. [Harmony](https://github.com/pardeike/Harmony)
When we want to use Harmony in a signed project, we must download the sources of Harmony & MonoMod, and compile it ourself.
Once there're updates in Harmony or MonoMod, we must do it again.
It's not a good idea, MonoMod should be signed, so that we can just use nuget to reference in our signed projects.

**Comment by nike4613** [comment] 2023-10-12 01:15
Duplicate of #81

**Closed as not planned by nike4613** 2023-10-12 01:15 UTC
Labels: enhancement

**Comment by CreateAndInject** [comment] 2023-10-12 01:18
> Duplicate of #81

Known issue keep years? Is this repo already dead?

**Comment by nike4613** [comment] 2023-10-12 01:25
I encourage you to read the Microsoft link in that issue. Notably, it includes

> ❌ DO NOT add, remove, or change the strong naming key.

Strong naming is also not really necessary (or even desirable) for MonoMod. In fact, the official guidance from Microsoft is for new projects to *not* use strong naming by default. Those that *need* it can and should sign the assemblies themselves, but it should be noted that there are no guarantees that this won't break MonoMod, because it's not tested in that configuration. (There are quite a few runtime internals that MonoMod pokes through, and the runtime simply taking a different path through the loader could break some behavior.)

**Comment by CreateAndInject** [comment] 2023-10-12 02:10
> I encourage you to read the Microsoft link in that issue. Notably, it includes
> 
> > ❌ DO NOT add, remove, or change the strong naming key.
> 
> Strong naming is also not really necessary (or even desirable) for MonoMod. In fact, the official guidance from Microsoft is for new projects to _not_ use strong naming by default. Those that _need_ it can and should sign the assemblies themselves, but it should be noted that there are no guarantees that this won't break MonoMod, because it's not tested in that configuration. (There are quite a few runtime internals that MonoMod pokes through, and the runtime simply taking a different path through the loader could break some behavior.)

Don't agree, if it's an exe project, you can unsign.
For library, almost all assemblies on nuget are signed, you can't demand people remove their strongname from their projects to use this nuget.
